#FROM指令：表示父静像，从哪个镜像拷贝
FROM centos:centos7.3.1511   

#此镜像维护者
MAINTAINER xxxx

#环境变量(可以定多个)
ENV TZ "Asia/Shanghai"
ENV TERM xterm

#ADD，COPY都可以复制文件到容器里，ADD命令比COPY命令多两个功能，拷贝压缩包可自动解压，COPY没有解压功能
ADD aliyun-mirror.repo /etc/yum.repos.d/CentOS-Base.repo
ADD aliyun-epel.repo /etc/yum.repos.d/epel.repo

#RUN命令每执行一个就会生成一层
RUN yum install -y lrzsz curl wget tar bzip2 unzip vim-enhanced passwd sudo yum-utils hostname net-tools rsync man && \
    yum install -y gcc gcc-c++ glibc git make automake cmake patch logrotate python-devel libpng-devel libjpeg-devel && \
    yum install -y --enablerepo=epel pwgen python-pip && \
    yum clean all

#安装进程管理工具
RUN pip install supervisor
#添加主配置文件
ADD supervisord.conf /etc/supervisord.conf

#创建目录
RUN mkdir -p /etc/supervisor.conf.d && \
    mkdir -p /var/log/supervisor

#对宿主机开放端口，宿主机会与容易端口做映射
EXPOSE 22

#多条ENTRYPOINT只有最后一条生效
ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]

#删除容器时不删除卷，宿主机目录映射容器目录
VOLUME ["/var/lib/mysql"]
